include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Otherwise cause the import of all_lint_rules to warn because of some
    # rules conflicts.
    # We explicitly enabled even conflicting rules and are fixing the conflict
    # in this file
    included_file_warning: ignore

linter:
  rules:
    # Incompatible with `prefer_final_locals`
    # Having immutable local variables makes larger functions more predictable
    # so we will use `prefer_final_locals` instead.
    unnecessary_final: false

    # Conflicts with `omit_local_variable_types` and other rules.
    # As per Dart guidelines, we want to avoid unnecessary types to make the
    # code more readable.
    always_specify_types: false

    # Conflicts with `prefer_single_quotes`
    # Single quotes are easier to type and don't compromise on readability.
    prefer_double_quotes: false

    # Conflict with retavily and hirechy grouping hierarchy
    sort_pub_dependencies: false

    # We don't really have public API
    public_member_api_docs: false

    # Adding final to praramters dosent make so diffrence and make differs from
    # implementation formate
    prefer_final_parameters: false

    # Conflicts with `prefer_relative_imports`
    always_use_package_imports: false

    # Boring as it sometimes force a line of 81 characters to be split in two.
    # As long as we try to respect that 80 characters limit, going slightly
    # above is fine.
    lines_longer_than_80_chars: false

    # Not quite suitable for Flutter, which may have a `build` method with a single
    # return, but that return is still complex enough that a "body" is worth it.
    prefer_expression_function_bodies: false

    # Too verbose with little value, and this is taken care of by the Flutter
    # devtool anyway.
    diagnostic_describe_all_properties: false

    # Personal preference. I prefer "if (bool) return;" over having it in
    # multiple lines
    always_put_control_body_on_new_line: false

    # False positive when using static members of class
    avoid_classes_with_only_static_members: false

    # Conflicts with the convention used by flutter, which puts `Key key`
    # and `@required Widget child` last.
    always_put_required_named_parameters_first: false
