name: go_responsive_annotation
description: A package for exposing annotations which used by go_responsive_generator.
version: 0.2.0
homepage: https://pub.dev/packages/go_responsive
repository: https://github.com/burhankhanzada/go_responsive
issue_tracker: https://github.com/burhankhanzada/go_responsive/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
