name: simple_example
description: A simple example to show usage of GoResponsive.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
  go_responsive: ^0.4.1
  go_responsive_annotation: ^0.4.1

dev_dependencies:
  build_runner: ^2.6.0
  go_responsive_generator: ^0.4.1

flutter:
  uses-material-design: true
