builders:
  go_responsive_builder:
    import: package:go_responsive_generator/go_responsive_generator.dart
    builder_factories: [goResponsiveBuilder]
    build_extensions: { '.dart': [.go_responsive.dart] }
    auto_apply: dependents
    build_to: source

targets:
  $default:
    sources:
    builders:
      go_responsive_generator|go_responsive_builder:
        enabled: true
        generate_for: 
          exclude:  [lib/firebase_options.dart]
