builders:
  go_responsive_builder:
    import: package:go_responsive_generator/go_responsive_generator.dart
    builder_factories: [goResponsiveBuilder]
    build_extensions: { '.dart': [.go_responsive.g.part] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]


targets:
  $default:
    sources:
    builders:
      go_responsive_generator|go_responsive_builder:
        enabled: true
