name: go_responsive_generator
description: A code generator for GoResponsive which generate useful extension methods and widget.
version: 0.3.0
homepage: https://pub.dev/packages/go_responsive
repository: https://github.com/burhankhanzada/go_responsive
issue_tracker: https://github.com/burhankhanzada/go_responsive/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  source_gen: ^1.4.0
  code_builder: ^4.8.0
  built_collection: ^5.1.1
  dart_style: ^2.3.4
  go_responsive_annotation: ^0.2.0
    
dev_dependencies:
  lints: ^3.0.0

