name: Publish to pub.dev

on:
  push:
    branches:
    - main

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: | 
          dart pub global activate melos
      - name: Publish
        run: melos publish
    # with:
    #   working-directory: path/to/package/within/repository